FPS = 60
BLOCK_SIZE = 16
WIDTH, HEIGHT = 800, 800
GRID_WIDTH = WIDTH // BLOCK_SIZE
GRID_HEIGHT = HEIGHT // BLOCK_SIZE

WATER_TERRAINS = ['ocean', 'deep_ocean']

MIN_BLOCK_HEAT = 1
MAX_BLOCK_HEAT = 32
AMPLITUDE = MAX_BLOCK_HEAT / 2
FREQUENCY = 0.05
OCTAVES = 3
LACUNARITY = 2
PERSISTENCE = 0.2